Advanced operations as cinema
FedmanCassad/GCDispatch pull request #1
Opened 2020-09-03 21:32 UTC by FedmanCassad

2020-09-04 02:34 UTC, nskazakov requested changes

2020-09-04 02:34 UTC, nskazakov commented on Week3TestWork/Code/BruteforceOperation.swift
> +  init(startIndexArray: [Int], endIndexArray: [Int], password: String, updateClousure:  @escaping (String) -> ()){
перед { нужен пробел

2020-09-04 02:34 UTC, nskazakov commented on Week3TestWork/Code/BruteforceOperation.swift
> +
лишние отступы

2020-09-04 02:34 UTC, nskazakov commented on Week3TestWork/Code/BruteforceOperation.swift
> +  var startIndexArray = [Int]()
сюда отступ в одну строку

2020-09-04 02:34 UTC, nskazakov commented on Week3TestWork/Code/BruteforceOperation.swift
> +import Foundation
после импорта отступ одна строка

2020-09-04 02:34 UTC, nskazakov commented on Week3TestWork/Code/BruteforceOperation.swift
> +  var iterations:Int = 0
перед указанием типа пробел после двоеточия

2020-09-04 02:34 UTC, nskazakov commented on Week3TestWork/Code/BruteforceOperation.swift
> +  var currentPassword:String?
пробел перед типом

2020-09-04 02:34 UTC, nskazakov commented on Week3TestWork/Code/BruteforceOperation.swift
> +  init(startIndexArray: [Int], endIndexArray: [Int], password: String, updateClousure:  @escaping (String) -> ()){
это Operation, а отсюда следует, что тебе не нужно делать замыкание. Достаточно просто завершить работу операции. Добавь еще проперти result, чтобы туда вписать найденное значение

2020-09-04 02:34 UTC, nskazakov commented on Week3TestWork/Code/ViewController.swift
> +      }
как-то слишком много кода. Надо подумать над оптимизацией

2020-09-04 05:58 UTC, FedmanCassad commented on Week3TestWork/Code/BruteforceOperation.swift
> +import Foundation
+

2020-09-04 05:59 UTC, FedmanCassad commented on Week3TestWork/Code/BruteforceOperation.swift
> +  var iterations:Int = 0
+

2020-09-04 05:59 UTC, FedmanCassad commented on Week3TestWork/Code/BruteforceOperation.swift
> +  init(startIndexArray: [Int], endIndexArray: [Int], password: String, updateClousure:  @escaping (String) -> ()){
+

2020-09-04 06:02 UTC, FedmanCassad commented on Week3TestWork/Code/BruteforceOperation.swift
> +  init(startIndexArray: [Int], endIndexArray: [Int], password: String, updateClousure:  @escaping (String) -> ()){
Никит, проверь лучше ветку feature/parallelism. Я ж вроде ссылку на нее присылал. Эта ветка - я изгалялся вчера вечером как мог, чтобы сделать реалтайм апдейт текстфилда, чтобы менялись перебираемые пароли. И пришел к выводу, что убегающий колбэк - лучший вариант. Точнее может и не лучший, но я понял наконец как удобно не прибегая к делегат-паттерну связать объекты разных классов.

2020-09-04 06:02 UTC, FedmanCassad commented on Week3TestWork/Code/BruteforceOperation.swift
> +
+

2020-09-04 06:03 UTC, FedmanCassad commented on Week3TestWork/Code/ViewController.swift
> +      }
В комплишн блок добавлен барьер как раз для того чтобы вовремя остановить остальные операции и прекратить обновление текстфилда с паролем на НАЙДЕННОМ пароле. Кароче в другой ветке все проще.

2020-09-07 02:33 UTC, nskazakov commented on Week3TestWork/Code/BruteforceOperation.swift
> +  var iterations:Int = 0
точка это согласен, исправил или не согласен?))

2020-09-07 04:32 UTC, FedmanCassad commented on Week3TestWork/Code/BruteforceOperation.swift
> +  var iterations:Int = 0
Согласен, испоавил)

2020-09-07 06:33 UTC, closed without merging